name: Cover the jobs details

on: 
 workflow_dispatch:

jobs:
  job-steps:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
              node-version: 20
      - name: job detail specification
        run: |
          npm ci && npm run test
          npm run build
        shell: bash
