name: run a step or job inside a container

on:
 workflow_dispatch:

jobs:
  step_container:
     runs-on: ubuntu-latest
     steps:
       - name: run test in VM
         run: echo "run test in VM."
       - name: run text in container
         uses: docker://alpine:3.8
         with:
           args: /bin/sh -c "echo Hello from Alpine."
       - name: run test in VM
         run: echo "run test in VM."

  job_container:
       runs-on: ubuntu-latest
       container:
         image: node:20
       steps:
         - name: check node -v
           run: node -v
